### ISSUE TITLE
`vagrant docker` doesn't work with `-H` flag

### ISSUE THREAD

**Issue by joefiorini** [fgrehm/vocker#16]
I have my Vagrantfile configured with the [`vagrant-managed-servers`](https://github.com/tknerr/vagrant-managed-servers) plugin. If I run `vagrant docker build .` I get an error that `/var/run/docker.sock` doesn't exist, as expected since I'm on a Mac. If I run `vagrant --provider=managed docker build .` I get the same error. Running `vagrant docker --provider=managed` gives an error because `--provider` isn't a valid docker command. Is it possible to give a provider name here?

**Comment by joefiorini** [comment]
I realized this is because I had docker configured to run over tcp, not socket. Unfortunately, I was unable to pass a `-H` to `vagrant docker`. I changed the daemon back to socket and it worked.

Perhaps vocker could allow a `config.host = 'whatever'` and automatically set -H in the docker command if it's provided?

**Comment by fgrehm** [comment]
Hum... makes sense :) What do you think about this:

``` ruby
Vagrant.configure("2") do |config|
  config.vm.hostname = 'docker-host'

  # Passes on '-H docker-host'
  config.docker_cmd.use_hostname = true

  # Passes on '-H other-host-or-ip'
  config.docker_cmd.host = 'other-host-or-ip'
end
```

I don't know how familiar you are with Vagrant's plugin architecture but if you can put up a PR I can review it later on and merge so that it makes into 0.4.0, otherwise I'll have a look at it once I free up my queue :)

To be really honest, I haven't been using the `vagrant docker` command as much as I thought I would, do you really see value in having that around? Right now it is basically a wrapper around `vagrant ssh -c "docker ...."`

**Comment by fgrehm** [comment]
The project is no longer being maintained, let's keep the issue tracker just for eventual bugs people might find.
